name: Release

# Configures this workflow to run every time a change is pushed to the master.
on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  libs_build:
    uses: ./.github/workflows/libs_generate.yml
    secrets: inherit

  android_build:
    needs: libs_build
    uses: ./.github/workflows/android_build.yml
    secrets: inherit

  ios_build:
    uses: ./.github/workflows/ios_build.yml
    secrets: inherit

  desktop_build:
    needs:
      - libs_build
    uses: ./.github/workflows/desktop_build.yml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    needs: [desktop_build, android_build, ios_build]
    permissions: write-all

    steps:
      - uses: actions/checkout@v2

      - name: Make release dir
        run: mkdir release

      - name: Download linux client
        uses: actions/download-artifact@master
        with:
          name: dobbyvpn-linux-amd64.zip
          path: release
      - name: Download windows client
        uses: actions/download-artifact@master
        with:
          name: dobbyvpn-windows.exe
          path: release
      - name: Download macos client
        uses: actions/download-artifact@master
        with:
          name: dobbyvpn-darwin-arm64
          path: release
      - name: Download android client
        uses: actions/download-artifact@master
        with:
          name: dobbyvpn-android.apk
          path: release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
